//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSuccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matiere
    {
        public int ID_Matiere { get; set; }
        public string Nom { get; set; }
        public Nullable<double> Prix { get; set; }
        public Nullable<int> ID_Paiement { get; set; }
        public Nullable<int> ID_Professeur { get; set; }
    
        public virtual Paiement Paiement { get; set; }
        public virtual Professeur Professeur { get; set; }
    }
}
